"""Regenerate decision_tables.py from Tieru's classic panel (admin_panel.py).

The bots' explained decisions (log.playerbot_listing / log.playerbot_equip) are
codes; their words live in Tieru's admin_panel.py, the reference
implementation. This script reads that file without running it: every
module-level DECISION_* constant is evaluated on its own (they are literals),
and the "ex_*" phrases that frame an explanation are taken from the language
dict the panel feeds into MAP_I18N. Only the Polish and English texts are kept,
the two languages this panel speaks.

Usage (admin_panel.py lives in the metin2-panel container on the server):
    docker exec metin2-panel cat /opt/panel/admin_panel.py > admin_panel.py
    python tools/generate_decision_tables.py admin_panel.py > decision_tables.py
"""
import ast
import pprint
import sys

LANGS = ("pl", "en")


def _strip_languages(value):
    """Keep only the pl/en slots of every {pl, en, de, tr} text dict."""
    if isinstance(value, dict):
        if "pl" in value and "en" in value and all(isinstance(k, str) for k in value):
            return {k: value[k] for k in LANGS if k in value}
        return {k: _strip_languages(v) for k, v in value.items()}
    if isinstance(value, tuple):
        return tuple(_strip_languages(v) for v in value)
    if isinstance(value, list):
        return [_strip_languages(v) for v in value]
    return value


def _constants(tree):
    found = {}
    for node in tree.body:
        if (isinstance(node, ast.Assign) and len(node.targets) == 1
                and isinstance(node.targets[0], ast.Name) and node.targets[0].id.startswith("DECISION_")):
            namespace = {}
            exec(compile(ast.Module([node], []), "admin_panel.py", "exec"), {"__builtins__": __builtins__}, namespace)
            found[node.targets[0].id] = namespace[node.targets[0].id]
    return found


def _explain_texts(tree):
    """The ex_* phrases per language, merged from every
    `for _lang, _texts in {"pl": {...}, ...}.items(): MAP_I18N[_lang].update(_texts)` block."""
    texts = {}
    for node in tree.body:
        if not isinstance(node, ast.For) or not isinstance(node.iter, ast.Call):
            continue
        func = node.iter.func
        if not (isinstance(func, ast.Attribute) and isinstance(func.value, ast.Dict)):
            continue
        try:
            languages = ast.literal_eval(func.value)
        except ValueError:
            continue
        for key in languages.get("pl", {}):
            if key.startswith("ex_"):
                texts[key] = {lang: languages[lang][key] for lang in LANGS if key in languages.get(lang, {})}
    if "ex_why_counter" not in texts:
        raise SystemExit("ex_* texts not found in admin_panel.py")
    return dict(sorted(texts.items()))


def main(path):
    source = open(path, encoding="utf-8").read()
    tree = ast.parse(source)
    tables = {name: _strip_languages(value) for name, value in sorted(_constants(tree).items())}
    tables["DECISION_TEXTS"] = _explain_texts(tree)
    out = ['"""Enum vocabularies and framing texts for log.playerbot_listing/log.playerbot_equip\'s decision',
           "codes (Playerbots 2.2.39+, \"the bots' explained decisions\"). GENERATED by",
           "tools/generate_decision_tables.py from Tieru's own classic admin_panel.py, the reference",
           "implementation (pl/en only) - do not edit by hand, regenerate after a Playerbots update.",
           'See decisions.py for the decode logic that uses these."""', ""]
    for name, value in tables.items():
        out.append("%s = %s" % (name, pprint.pformat(value, width=120, sort_dicts=True)))
        out.append("")
    sys.stdout.reconfigure(encoding="utf-8")
    sys.stdout.write("\n".join(out))


if __name__ == "__main__":
    main(sys.argv[1])
